# This is a basic workflow to help you get started with Actions

name: 環境変数を確認

# Controls when the workflow will run
on:
    # ワークフローはマニュアル実行できます。
    workflow_dispatch:

    # あらゆるコミットに対して実行します。
    push:
        branches: "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v3
            with:
                ref: ${{ github.event.pull_request.head.ref }}

            # Runs a single command using the runners shell
          - name: 環境の確認
            run: |
                env
