name: Pull Request を自動的にアサインする

on:
    pull_request:
        # Pull Request もしくは Draft を作成したときに動かします。
        types: "opened"

jobs:
    assign:
        name: Set assignees
        runs-on: ubuntu-latest
        steps:
            # ========== SHELL SCRIPT ==========
          - name: Set assignees
            env:
                # 誰にアサインするのか
                ASSIGNEES: "${{ github.actor }}"
            run: |
                assignee_count=$(cat ${{ github.event_path }} | jq '.pull_request.assignees | length')
                if [[ 0 == $assignee_count ]]; then
                    assignees=$(echo "\"${ASSIGNEES// /}\"" | jq 'split(",")')
                    curl -X POST \
                         -H "Content-Type: application/json" \
                         -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                         -d "{ \"assignees\": $assignees }" \
                         https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees
                fi
            # ========== PERL SCRIPT ==========
          - name: Perl Script

          - name: Setup Perl environment
            # You may pin to the exact commit or the version.
            # uses: shogo82148/actions-setup-perl@15188b90fb15594cb12e018dd720024a7378bcd8
            uses: shogo82148/actions-setup-perl@v1.15.0
            with:
                  # The Perl version to download (if necessary) and use. Example: 5.30.0
                  perl-version: # optional, default is 5
  
                  distribution: # optional, default is default

                  # enables multi threading options(-Duseithreads).
      
                  multi-thread: # optional

                  # install CPAN modules from your cpanfile with the specified installer.
                  install-modules-with: # optional

                  # extra argument for CPAN module installer.
                  install-modules-args: # optional

                  # List of one or more CPAN modules, separated by a newline \n character.
                  install-modules: # optional

                  # enable caching when install CPAN modules.
                  enable-modules-cache: # optional, default is true

                  # working directory.
                  working-directory: # optional, default is .
