name: コミットファイルを自動的に追加する

on:
    pull_request:
        # Pull Request もしくは Draft を作成したときに動かします。
        types: "opened"

jobs:

    # ========== 環境の診断 ==========
    show-env:
        name: 環境の診断
        runs-on: ubuntu-latest
        steps:
            # ========== SHELL SCRIPT ==========
          - name: Show Environment
            run: |
                echo "[INFO] --- 状況確認 ---"
                echo "CURRENT DIRECTORY: [`pwd`]"

                echo
                echo "[INFO] --- 環境変数 ---"
                env

                echo
                echo "[INFO] --- ディレクトリ一覧 ---"
                find . -type d | xargs /bin/ls -ldF --full-time

    # ========== コミットファイルを自動的に追加します ==========
    generate-tmp:
        name: コミットファイルを自動的に追加します
        runs-on: ubuntu-latest
        steps:
            # ========== SHELL SCRIPT ==========
          - name: Set assignees
            run: |
                cd batches/20-generate-tmp/
                go run main.go
