name: コミットファイルを自動的に追加する

on:
    pull_request:
        # Pull Request もしくは Draft を作成したときに動かします。
        types: "opened"
    push:
        branches:
          - 'mass10/**'

jobs:

    # ========== 環境の診断 ==========
    show-env:
        name: 環境の診断
        runs-on: ubuntu-latest
        steps:
            # ========== SHELL SCRIPT ==========
          - name: Show Environment
            run: |
                echo "[INFO] --- 状況確認 ---"
                echo "CURRENT DIRECTORY: [`pwd`]"

                echo
                echo "[INFO] --- 環境変数 ---"
                env

                echo
                echo "[INFO] --- ディレクトリ一覧 ---"
                find "$RUNNER_WORKSPACE" | xargs /bin/ls -ldF --full-time

                echo
                echo "[INFO] --- GitHub ファイル一覧 ---"
                find "$GITHUB_ENV" -type f | xargs /bin/ls -ldF --full-time

                echo
                echo "[INFO] --- 作業ディレクトリの確認 ---"
                find ~/ -type f -name main.go -ls

    # ========== コミットファイルを自動的に追加します ==========
    generate-tmp:
        name: コミットファイルを自動的に追加します
        runs-on: ubuntu-latest
        steps:
            # ========== SHELL SCRIPT ==========
          - name: Set assignees
            working-directory: batches/20-generate-tmp/
            run: |
                go run main.go
